# Generated by Django 4.2 on 2023-04-11 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='email_verified',
        ),
        migrations.AddField(
            model_name='user',
            name='status',
            field=models.CharField(choices=[('COMPLETE', 'Complete'), ('PENDING_EXTRA_DATA', 'Pending Complete Data')], default='PENDING_EXTRA_DATA', max_length=20),
        ),
        migrations.AlterField(
            model_name='user',
            name='telephone',
            field=models.CharField(blank=True, max_length=20, unique=True),
        ),
    ]
