name: Docker Compose Actions Workflow
on: push
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: SpicyPizza/create-envfile@v1.3
      - name: Make envfile
        with:
          envkey_DEBUG: True
          envkey_POSTGRES_PASSWORD: somerandompassword
          envkey_SECRET_KEY: anotherrandomstring
          envkey_ALLOWED_HOSTS: localhost
          envkey_DJANGO_CORS_ALLOWED_ORIGINS: http://localhost:5000
          envkey_DJANGO_CSFR_TRUSTED_ORIGINS: http://localhost:5000
          envkey_EMAIL_HOST: smtp.gmail.com
          envkey_EMAIL_HOST_USER: ecommercebackend00@gmail.com
          envkey_EMAIL_HOST_PASSWORD: 1234567890
          envkey_EMAIL_PORT: 587
          envkey_STRIPE_SECRET_KEY: sk_test_51IY2
          envkey_STRIPE_PUBLISHABLE_KEY: pk_test_51IY2
      - uses: actions/checkout@v2
      - name: Build the stack
        run: docker-compose -f docker-compose-local-dev.yml up --build
